
import numpy as np
import matplotlib.pyplot as plt
b =[]
x,y = np.loadtxt('rw_results_0.dat', unpack = True)
b = y.tolist()
a = x.tolist()
x,y = np.loadtxt('rw_results_1.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_2.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_3.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_4.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_5.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_6.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_7.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_8.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_9.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_10.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_11.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_12.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_13.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_14.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_15.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_16.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_17.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_18.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
x,y = np.loadtxt('rw_results_19.dat', unpack = True)
b.extend(y.tolist())
a.extend(x.tolist())
plt.xlim((0, 8))
plt.ylim((0, 3000))
plt.figure(figsize=(10,8))
plt.xlabel('Dimension')
plt.ylabel('Distance from origin')
plt.scatter(a,b)
plt.savefig('rw_results.png')

